### ISSUE TITLE
Implement pre-commit hooks and development environment standardization

### ISSUE THREAD

**Issue by dandye** [chronicle/logstory#13]
## Summary

To improve developer experience and code quality, we should implement pre-commit hooks and standardize the development environment setup.

## Current Development Pain Points

- **Inconsistent code style**: Developers may commit code that fails CI linting
- **Manual quality checks**: No automated validation before commits
- **Environment variations**: Different developer setups lead to \"works on my machine\" issues
- **Missing editor config**: No standardized editor settings

### Phase 1: Pre-commit Infrastructure
- [ ] Add `pre-commit` framework to development dependencies
- [ ] Configure pre-commit hooks for:
  - [ ] Ruff linting and formatting
  - [ ] YAML validation
  - [ ] Trailing whitespace removal
  - [ ] Large file detection
  - [ ] Secret detection (basic patterns)

### Phase 2: Development Environment
- [ ] Create `.devcontainer` configuration for VS Code
- [ ] Add `.editorconfig` for consistent editor settings
- [ ] Create `Makefile` with common development tasks:
  - [ ] `make setup` - Install dependencies and pre-commit hooks
  - [ ] `make test` - Run full test suite
  - [ ] `make lint` - Run linting checks
  - [ ] `make clean` - Clean build artifacts

### Phase 3: Developer Documentation
- [ ] Create `CONTRIBUTING.md` with development setup instructions
- [ ] Add development environment setup to main documentation
- [ ] Document code review guidelines and standards
- [ ] Create debugging guides for common issues

### Phase 4: Enhanced Tooling
- [ ] Add dependency vulnerability scanning in pre-commit
- [ ] Create commit message templates
- [ ] Add git hooks for branch naming conventions
- [ ] Implement automated changelog entry validation

## Example Pre-commit Configuration

```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
```

## Benefits

- **Faster feedback**: Catch issues before CI/CD pipeline
- **Consistent quality**: All commits meet minimum standards
- **Reduced CI failures**: Less back-and-forth in pull requests
- **Better onboarding**: New contributors get consistent setup experience
- **Time savings**: Automated checks reduce manual review burden

## Acceptance Criteria

- [ ] Pre-commit hooks run on every commit
- [ ] Hooks complete in <30 seconds
- [ ] Development setup works in fresh environment
- [ ] Clear documentation for contributor setup
- [ ] CI pipeline validates pre-commit hooks are configured

🤖 Generated with [Claude Code](https://claude.ai/code)
