### ISSUE TITLE
Implement automated release pipeline with semantic versioning

### ISSUE THREAD

**Issue by dandye** [chronicle/logstory#15]
## Summary

LogStory currently uses manual release processes which can be error-prone and inconsistent. Implementing an automated release pipeline with semantic versioning will improve reliability and reduce maintenance overhead.

## Current Release Process Issues

- **Manual version bumping**: Error-prone and easy to forget
- **Inconsistent changelog**: No standardized format or automation
- **No release validation**: Changes go live without smoke testing
- **Manual PyPI publishing**: Potential for human error
- **No rollback procedures**: No clear process for reverting problematic releases

### Phase 1: Semantic Versioning Setup
- [ ] Implement conventional commit message format
- [ ] Add `semantic-release` or similar tooling
- [ ] Configure automatic version bumping based on commit types:
  - `feat:` → minor version bump
  - `fix:` → patch version bump  
  - `BREAKING CHANGE:` → major version bump
- [ ] Update documentation with commit message guidelines

### Phase 2: Automated Changelog
- [ ] Generate changelog automatically from commit messages
- [ ] Include breaking changes, features, and bug fixes
- [ ] Link to related issues and pull requests
- [ ] Maintain changelog in `CHANGELOG.md`

### Phase 3: Release Pipeline
- [ ] Create GitHub Action for automated releases on main branch
- [ ] Add release validation with smoke tests
- [ ] Implement automated PyPI publishing
- [ ] Create GitHub releases with generated release notes
- [ ] Add release artifact validation

### Phase 4: Release Quality Gates
- [ ] Require all CI checks to pass before release
- [ ] Add manual approval step for major releases
- [ ] Implement release candidate process for major versions
- [ ] Add automated rollback triggers for failed releases

## Example Release Workflow

```yaml
name: Release
on:
  push:
    branches: [main]
    
jobs:
  release:
    if: \"\!contains(github.event.head_commit.message, 'chore(release)')\"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Run tests
        run: |
          pip install -e .
          pytest
          
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
```

## Release Process Documentation

- [ ] Create release checklist for maintainers
- [ ] Document rollback procedures
- [ ] Add troubleshooting guide for release issues
- [ ] Create security release process documentation

## Conventional Commit Examples

```bash
feat: add support for custom timestamp formats
fix: resolve memory leak in large file processing
docs: update installation instructions
chore: bump dependency versions
BREAKING CHANGE: remove deprecated API methods
```

## Benefits

- **Consistent releases**: Automated process reduces human error
- **Clear versioning**: Semantic versioning communicates change impact
- **Faster releases**: No manual steps means quicker bug fixes
- **Better documentation**: Automated changelog keeps users informed
- **Release confidence**: Validation steps catch issues before publication

## Acceptance Criteria

- [ ] Releases are triggered automatically on main branch merges
- [ ] Version numbers follow semantic versioning strictly
- [ ] Changelog is generated and updated automatically
- [ ] PyPI packages are published without manual intervention
- [ ] Release validation includes smoke tests
- [ ] Rollback procedures are documented and tested

🤖 Generated with [Claude Code](https://claude.ai/code)
